### PR TITLE
Fix Typos In Changes File: "0,76" and "nwatkins"

### PR DESCRIPTION
**Pull request by wbraswell**

### CODE REVIEW

**Comment by wbraswell** [comment]
@rurban 
I need to be set as an owner in the github Perl11 group so that I don't have to ask permission to write files to Perl11 repos.

**Comment by rurban** [comment]
Oops, the mongers group was missing. Done

**Comment by wbraswell** [comment]
@rurban 
I am still listed as a "member" not an "owner" here:
https://github.com/orgs/perl11/people

**Comment by rurban** [comment]
All Mongers have owner rights

**Comment by wbraswell** [comment]
I'm not talking about Mongers, I'm taking about Perl 11.
Click this link.  You will see my name is listed as "member" not "owner".
https://github.com/orgs/perl11/people

**Comment by rurban** [comment]
Ingy is the owner, talk to him.

**Pull request merged**
